/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialog;

import entity.KhuyenMai;
import gui.swing.CustomJOptionPane;

import static java.lang.Boolean.FALSE;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import Interface.KhuyenMaiDao;
import Interface.impl.KhuyenMaiImpl;
import connectDB.DatabaseManager;

/**
 * @author 84343
 */
public class DL_ThemKhuyenMai extends javax.swing.JDialog {

	private KhuyenMaiDao km_dao;

	public DL_ThemKhuyenMai(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		km_dao = new KhuyenMaiImpl();
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblThemMH = new javax.swing.JLabel();
		btnExit = new gui.swing.Button();
		lblMoTa = new javax.swing.JLabel();
		txtMoTa = new javax.swing.JTextField();
		lblMucGiam = new javax.swing.JLabel();
		btnThem = new gui.swing.RadiusButton();
		btnThoat = new gui.swing.RadiusButton();
		cboMucGiam = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtBatDau = new com.toedter.calendar.JDateChooser();
		txtKetThuc = new com.toedter.calendar.JDateChooser();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		lblThemMH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
		lblThemMH.setForeground(new java.awt.Color(41, 173, 86));
		lblThemMH.setText("KHUYẾN MÃI MỚI");

		btnExit.setBackground(new java.awt.Color(255, 0, 51));
		btnExit.setBorder(null);
		btnExit.setForeground(new java.awt.Color(255, 255, 255));
		btnExit.setText("  X  ");
		btnExit.setEffectColor(new java.awt.Color(255, 255, 255));
		btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});

		lblMoTa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblMoTa.setText("Mô tả:");

		txtMoTa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtMoTaActionPerformed(evt);
			}
		});

		lblMucGiam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblMucGiam.setText("Mức giảm");

		btnThem.setBackground(new java.awt.Color(41, 173, 86));
		btnThem.setForeground(new java.awt.Color(255, 255, 255));
		btnThem.setText("Thêm");
		btnThem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemActionPerformed(evt);
			}
		});

		btnThoat.setBackground(new java.awt.Color(255, 51, 51));
		btnThoat.setForeground(new java.awt.Color(255, 255, 255));
		btnThoat.setText("Thoát");
		btnThoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThoatActionPerformed(evt);
			}
		});

		cboMucGiam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "50", "70", "100" }));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel1.setText("Bắt đầu");

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel2.setText("Kết thúc");

		txtBatDau.setDate(new Date());
		txtBatDau.setDateFormatString("dd-MM-yyyy hh:mm");
		txtBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtBatDau.setOpaque(false);
		txtBatDau.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				txtBatDauPropertyChange(evt);
			}
		});

		txtKetThuc.setDate(new Date());
		txtKetThuc.setDateFormatString("dd-MM-yyyy hh:mm");
		txtKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtKetThuc.setOpaque(false);
		txtKetThuc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				txtKetThucPropertyChange(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout
								.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(lblThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 189,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(102, 102, 102).addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(25, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
										javax.swing.GroupLayout.Alignment.LEADING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(txtMoTa,
														javax.swing.GroupLayout.PREFERRED_SIZE, 306,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
												.createSequentialGroup().addGap(75, 75, 75)
												.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(96, 96, 96).addComponent(btnThoat,
														javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel1Layout.createSequentialGroup()
																.addComponent(lblMucGiam,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 99,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
																68, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(49, 49, 49)))
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE,
																181, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cboMucGiam,
																javax.swing.GroupLayout.PREFERRED_SIZE, 154,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtKetThuc,
																javax.swing.GroupLayout.PREFERRED_SIZE, 181,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(125, 125, 125)))
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(23, 23, 23)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(lblThemMH,
								javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(28, 28, 28)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMucGiam)
								.addComponent(cboMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(txtKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(23, 23, 23)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnExitActionPerformed

	private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMoTaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtMoTaActionPerformed

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed

		DatabaseManager db = DatabaseManager.getInstance();
		db.connect();

		try {
			db.connect();
			String maNV = phatSinhMaKM();
			String moTa = txtMoTa.getText();
			SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
			Date selectedDate = txtBatDau.getDate();
			String formattedDate = dateFormat.format(selectedDate);
			txtBatDau.setDateFormatString("yyyy-MM-dd");

			SimpleDateFormat simple = new SimpleDateFormat("yyyy-MM-dd");
			java.util.Date chooser = txtBatDau.getDate();
			String corect = simple.format(chooser);
			java.util.Date utilDate = null;
			try {
				utilDate = dateFormat.parse(corect);
			} catch (ParseException e1) {
				e1.printStackTrace();
			}
			java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

			Date selectedDate2 = txtKetThuc.getDate();
			String formattedDate2 = dateFormat.format(selectedDate2);
			txtKetThuc.setDateFormatString("yyyy-MM-dd");

			java.util.Date chooser2 = txtKetThuc.getDate();
			String corect2 = simple.format(chooser2);
			java.util.Date utilDate2 = null;
			try {
				utilDate2 = dateFormat.parse(corect2);
			} catch (ParseException e1) {
				e1.printStackTrace();
			}
			java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());

			LocalDate batDau = sqlDate.toLocalDate();
			LocalDate ketThuc = sqlDate2.toLocalDate();
//            System.out.println(batDau);
//            System.out.println(ketThuc);

			String mucGiamString = (String) cboMucGiam.getSelectedItem(); // Lấy chuỗi mức giảm từ thành phần JComboBox
			Double mucGiam = Double.parseDouble(mucGiamString); // Chuyển đổi chuỗi thành Double
			KhuyenMai km = new KhuyenMai(maNV, moTa, batDau, ketThuc, mucGiam);

			Boolean isSuccess = km_dao.createKhuyenMai(km);

			if (isSuccess) {
				JOptionPane.showMessageDialog(null, "Thêm thành công");
			} else {
				CustomJOptionPane.showMessageDialog("Thêm khuyến mãi không thành công !");
			}
		} catch (Exception ex) {
			Logger.getLogger(DL_ThemKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnThemActionPerformed

	private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		this.dispose();
		return;
	}// GEN-LAST:event_btnThoatActionPerformed

	private void txtBatDauPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_txtBatDauPropertyChange
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		Date selectedDate = txtBatDau.getDate();
		String formattedDate = dateFormat.format(selectedDate);
		txtBatDau.setDateFormatString("yyyy-MM-dd");

		SimpleDateFormat simple = new SimpleDateFormat("yyyy-MM-dd");
		java.util.Date chooser = txtBatDau.getDate();
		String corect = simple.format(chooser);
		java.util.Date utilDate = null;
		try {
			utilDate = dateFormat.parse(corect);
		} catch (ParseException e1) {
			e1.printStackTrace();
		}
		java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

	}// GEN-LAST:event_txtBatDauPropertyChange

	private void txtKetThucPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_txtKetThucPropertyChange
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		Date selectedDate = txtKetThuc.getDate();
		String formattedDate = dateFormat.format(selectedDate);
		txtKetThuc.setDateFormatString("yyyy-MM-dd");

		SimpleDateFormat simple = new SimpleDateFormat("yyyy-MM-dd");
		java.util.Date chooser = txtKetThuc.getDate();
		String corect = simple.format(chooser);
		java.util.Date utilDate = null;
		try {
			utilDate = dateFormat.parse(corect);
		} catch (ParseException e1) {
			e1.printStackTrace();
		}
		java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
	}// GEN-LAST:event_txtKetThucPropertyChange

	public String phatSinhMaKM() {
		List<KhuyenMai> kms = km_dao.getAllKhuyenMai();
		String temp = null;

		for (KhuyenMai km : kms) {
			temp = km.getMaKM();
		}
		int count = laySoDuoi(temp);
		count++;

		String maKM = String.format("KM%03d", count);
		return maKM;
	}

	public int laySoDuoi(String str) {
		if (str == null) {
			return 0;
		} else {
			String numberStr = str.substring(2);// Loại bỏ kí tự "KM"
			int number = Integer.parseInt(numberStr);
			return number;
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DL_ThemKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DL_ThemKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DL_ThemKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DL_ThemKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DL_ThemKhuyenMai dialog = new DL_ThemKhuyenMai(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private gui.swing.Button btnExit;
	private gui.swing.RadiusButton btnThem;
	private gui.swing.RadiusButton btnThoat;
	private javax.swing.JComboBox<String> cboMucGiam;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblMoTa;
	private javax.swing.JLabel lblMucGiam;
	private javax.swing.JLabel lblThemMH;
	private com.toedter.calendar.JDateChooser txtBatDau;
	private com.toedter.calendar.JDateChooser txtKetThuc;
	private javax.swing.JTextField txtMoTa;
	// End of variables declaration//GEN-END:variables
}
